services:
  mariadb:
    image: mariadb:11.8
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: b5cdca33223fed57be2b84f9639b4a52
      MARIADB_DATABASE: oliver_rein
      MARIADB_USER: user
      MARIADB_PASSWORD: 537b205972ec1f3d5abd43e1e7d9783a
    volumes:
      - mariadb_data:/var/lib/mysql
      #- ./backup.sql:/docker-entrypoint-initdb.d/backup.sql:ro  # <--- Backup als Init-Script
    networks:
      - laravel

  app:
    build: .
    depends_on:
      - mariadb
    ports:
      - "8085:8085"
    networks:
      - laravel
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PHP_ENABLE_OPCACHE=no
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=oliver_rein
      - DB_USERNAME=user
      - DB_PASSWORD=537b205972ec1f3d5abd43e1e7d9783a
    command: >
      bash -c "
        composer install &&
        php artisan config:clear &&
        php artisan serve --host=0.0.0.0 --port=8085
      "

volumes:
  mariadb_data:

networks:
  laravel:
